'use strict';
const KEY='brief-standalone-v1';
const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleString('sv-SE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const app=document.getElementById('app');
const initial=()=>{const at=now();return {people:[{id:'johan',name:'Johan Andersson',role:'admin'},{id:'erik',name:'Erik Svensson',role:'employee'},{id:'marcus',name:'Marcus Jansson',role:'employee'},{id:'sara',name:'Sara Nilsson',role:'employee'}],customers:[{id:'sala',name:'Salabostäder AB',prefix:'1842'},{id:'kommun',name:'Sala kommun',prefix:'2501'},{id:'mimer',name:'Mimer Fastigheter',prefix:'3814'}],customerProjects:['2501-184','3814-042','2501-221'],projects:[{id:'p1',number:'1842-026',customerProject:'2501-184',name:'Badrumsrenovering',address:'Storgatan 12, Sala',customer:'sala',comment:'Nycklar finns på kontoret.',orders:[{id:'o1',title:'Rivning befintligt badrum',description:'Rivning av befintligt badrum inklusive tätskikt, inredning och golv. Skydda angränsande ytor.',assignee:'erik',priority:'Normal',due:'2026-10-10',status:'Ej påbörjad',issuedBy:'johan',issuedAt:at,acceptedAt:null,participants:[],notes:[],events:[{id:id(),at,text:'Johan Andersson skapade arbetsordern.'},{id:id(),at,text:'Johan Andersson skickade arbetsordern till Erik Svensson.'}]}]},{id:'p2',number:'3814-118',customerProject:'3814-042',name:'Köksrenovering',address:'Stationsvägen 3, Västerås',customer:'mimer',comment:'Arbetsorder behöver skapas.',orders:[]}]};};
let data;try{data=JSON.parse(localStorage.getItem(KEY));if(!data||!Array.isArray(data.projects)||!Array.isArray(data.people)||!Array.isArray(data.customers)||!Array.isArray(data.customerProjects))data=initial();}catch{data=initial();}
let user='johan',screen='projects',pid='',oid='',tab='Översikt',query='',filter='Alla',draft={},pendingFiles=[];
const person=()=>data.people.find(p=>p.id===user);
const admin=()=>person().role==='admin';
const name=u=>data.people.find(p=>p.id===u)?.name||'Okänd';
const project=()=>data.projects.find(p=>p.id===pid);
const order=()=>project()?.orders.find(o=>o.id===oid);
const relevant=o=>admin()||o.assignee===user||o.participants.some(p=>p.user===user);
const canWork=o=>admin()||(o.assignee===user&&o.acceptedAt)||o.participants.some(p=>p.user===user&&p.acceptedAt);
const status=p=>p.orders.length&&p.orders.every(o=>o.status==='Slutförd')?'Slutförd':p.orders.some(o=>o.status==='Pågående')?'Pågående':'Ej påbörjad';
const customer=p=>data.customers.find(c=>c.id===p.customer)?.name||'Okänd';
const badge=s=>`<span class="badge ${s==='Slutförd'?'green':s==='Pågående'?'yellow':'red'}">${esc(s)}</span>`;
const notice=t=>document.getElementById('notice').textContent=t;
function save(next){try{localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch{notice('Lagringsutrymmet är fullt. Ändringen sparades inte. Välj mindre filer.');return false;}}
function mutate(fn,text){const next=structuredClone(data),o=next.projects.find(p=>p.id===pid).orders.find(o=>o.id===oid);fn(o);o.events.push({id:id(),at:now(),text:`${name(user)} ${text}`});if(save(next))render();}
function bind(selector,event,fn){app.querySelectorAll(selector).forEach(el=>el.addEventListener(event,fn));}
const field=(label,control)=>`<label><span>${label}</span>${control}</label>`;
const input=(key,value='',extra='')=>`<input name="${key}" value="${esc(value)}" ${extra}>`;
const filesHtml=files=>`<div class="files">${files.map(f=>`<a download="${esc(f.name)}" href="${esc(f.data)}">${f.type.startsWith('image/')?`<img src="${esc(f.data)}" alt="${esc(f.name)}">`:'<div class="file-placeholder">↧</div>'}<span>${esc(f.name)}</span></a>`).join('')}</div>`;
function render(){
 const selector=document.getElementById('user');selector.innerHTML=data.people.map(p=>`<option value="${p.id}">${esc(p.name)} · ${p.role==='admin'?'Arbetsledare':'Utförare'}</option>`).join('');selector.value=user;
 document.getElementById('newBtn').hidden=!admin();document.getElementById('navNew').hidden=!admin();document.getElementById('navAdmin').hidden=!admin();
 if(screen==='projects')list();if(screen==='project')projectView();if(screen==='order')orderView();if(screen==='new')newOrder();if(screen==='review')review();if(screen==='admin')administration();
}
function list(){const visible=data.projects.filter(p=>admin()||p.orders.some(relevant));const rows=visible.filter(p=>(filter==='Alla'||status(p)===filter)&&`${p.number} ${p.name} ${p.customerProject} ${p.address} ${customer(p)} ${p.orders.map(o=>name(o.assignee)).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 app.innerHTML=`<h1>Projekt</h1><p class="muted">Översikt över aktuella projekt och arbetsorder</p><div class="search"><input id="search" aria-label="Sök projekt" placeholder="⌕ Sök projekt, adress, beställare eller utförare…" value="${esc(query)}"></div><div class="filters">${['Alla','Ej påbörjad','Pågående','Slutförd'].map(s=>`<button data-filter="${s}" class="${filter===s?'active':''}">${s} <b>${s==='Alla'?visible.length:visible.filter(p=>status(p)===s).length}</b></button>`).join('')}</div><div class="table-scroller"><section class="projectlist"><div class="projectrow head">${['Kundprojektnr','Projektnr','Adress','Projektnamn','Utförare','Status','Kommentar'].map(x=>`<span>${x}</span>`).join('')}</div>${rows.map(p=>`<button class="projectrow row-button" data-project="${p.id}"><span>${esc(p.customerProject)}</span><span>${esc(p.number)}</span><span>${esc(p.address)}</span><span>${esc(p.name)}</span><span>${esc([...new Set(p.orders.filter(relevant).map(o=>name(o.assignee)))].join(', ')||'—')}</span><span>${badge(status(p))}</span><span class="comment">${esc(p.comment||'—')}</span></button>`).join('')}</section></div>${!rows.length?'<div class="empty">Inga projekt hittades.</div>':''}<p class="brand-note">Brief — uttalas brēf. Ordning i arbetet.</p>`;
 bind('#search','input',e=>{query=e.target.value;const pos=e.target.selectionStart;list();const el=app.querySelector('#search');el.focus();el.setSelectionRange(pos,pos);});bind('[data-filter]','click',e=>{filter=e.currentTarget.dataset.filter;list();});bind('[data-project]','click',e=>{pid=e.currentTarget.dataset.project;screen='project';render();});}
function projectView(){const p=project();app.innerHTML=`<button class="back" data-back>← Projektöversikt</button><small>${esc(p.number)} · ${esc(customer(p))}</small><h1>${esc(p.name)}</h1><p class="muted">${esc(p.address)} · Kundprojekt ${esc(p.customerProject)}</p>${badge(status(p))}<p>${esc(p.comment)}</p><div class="list">${p.orders.filter(relevant).map(o=>`<button class="order row-button" data-order="${o.id}"><span><small>${esc(name(o.assignee))} · Senast ${esc(o.due)}</small><strong>${esc(o.title)}</strong></span>${badge(o.status)}<span>›</span></button>`).join('')||'<div class="empty">Inga arbetsorder ännu.</div>'}</div>${admin()?'<button class="primary full" data-new>＋ Ny arbetsorder i projektet</button>':''}`;
 bind('[data-back]','click',()=>{screen='projects';render();});bind('[data-order]','click',e=>{oid=e.currentTarget.dataset.order;screen='order';tab='Översikt';pendingFiles=[];render();});bind('[data-new]','click',()=>beginNew(pid));}
function beginNew(projectId=''){draft={projectId,number:'',customerProject:'',name:'',address:'',comment:'',title:'',description:'',due:new Date().toISOString().slice(0,10),priority:'Normal',assignee:'erik'};if(projectId){const p=data.projects.find(p=>p.id===projectId);Object.assign(draft,{number:p.number,customerProject:p.customerProject,name:p.name,address:p.address,comment:p.comment});}screen='new';render();}
function newOrder(){if(!admin())return;app.innerHTML=`<button class="back" data-back>← Projektöversikt</button><h1>Ny arbetsorder</h1><form class="card form" id="orderForm">${field('Projekt',`<select name="projectId"><option value="">Skapa nytt projekt</option>${data.projects.map(p=>`<option value="${p.id}" ${draft.projectId===p.id?'selected':''}>${esc(p.number)} · ${esc(p.name)}</option>`).join('')}</select>`)}${!draft.projectId?`${field('Kundprojektnummer',input('customerProject',draft.customerProject,'required list="customerProjects"'))}<datalist id="customerProjects">${data.customerProjects.map(p=>`<option value="${esc(p)}"></option>`).join('')}</datalist>${field('Eget projektnummer',input('number',draft.number,'required pattern="[0-9]{4}-.+" placeholder="1842-026"'))}<div class="auto" id="customerMatch"></div>${field('Adress',input('address',draft.address,'required'))}${field('Projektnamn',input('name',draft.name,'required'))}${field('Projektkommentar (valfri)',input('comment',draft.comment))}`:''}${field('Arbetsorderrubrik',input('title',draft.title,'required'))}${field('Arbetsbeskrivning',`<textarea name="description" required>${esc(draft.description)}</textarea>`)}<div class="two">${field('Klart senast',input('due',draft.due,'type="date" required'))}${field('Prioritet',`<select name="priority">${['Låg','Normal','Hög'].map(s=>`<option ${draft.priority===s?'selected':''}>${s}</option>`).join('')}</select>`)}</div>${field('Ansvarig utförare',`<select name="assignee" required>${data.people.filter(p=>p.role==='employee').map(p=>`<option value="${p.id}" ${draft.assignee===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`)}<button class="primary full">Granska arbetsorder →</button></form>`;
 const form=app.querySelector('form');const match=()=>{const el=app.querySelector('#customerMatch');if(el)el.textContent=data.customers.find(c=>c.prefix===form.elements.number.value.slice(0,4))?.name||'De fyra första siffrorna identifierar beställaren.';};match();bind('[name="number"]','input',match);
 bind('[name="projectId"]','change',e=>{Object.assign(draft,Object.fromEntries(new FormData(form)));draft.projectId=e.target.value;if(draft.projectId){const p=data.projects.find(p=>p.id===draft.projectId);Object.assign(draft,{number:p.number,customerProject:p.customerProject,address:p.address,name:p.name,comment:p.comment});}else Object.assign(draft,{number:'',customerProject:'',address:'',name:'',comment:''});newOrder();});
 bind('#orderForm','submit',e=>{e.preventDefault();Object.assign(draft,Object.fromEntries(new FormData(form)));if(!draft.projectId&&!data.customers.some(c=>c.prefix===draft.number.slice(0,4))){notice('Registrera beställarprefixet under Team & beställare först.');return;}if(!draft.projectId&&data.projects.some(p=>p.number.toLowerCase()===draft.number.trim().toLowerCase())){notice('Projektnumret finns redan. Välj befintligt projekt.');return;}screen='review';render();});bind('[data-back]','click',()=>{screen='projects';render();});}
function review(){app.innerHTML=`<button class="back" data-edit>← Ändra arbetsorder</button><h1>Granska arbetsorder</h1><div class="card"><h2>${esc(draft.title)}</h2><p class="description">${esc(draft.description)}</p><div class="info">${[['Projekt',`${draft.number} · ${draft.name}`],['Kundprojekt',draft.customerProject],['Adress',draft.address],['Utförare',name(draft.assignee)],['Datum / prioritet',`${draft.due} · ${draft.priority}`]].map(([label,value])=>`<p><small>${label}</small><b>${esc(value)}</b></p>`).join('')}</div><button class="primary full" id="send">Skicka arbetsorder ↗</button></div>`;bind('[data-edit]','click',()=>{screen='new';render();});bind('#send','click',()=>{const next=structuredClone(data);let p=next.projects.find(p=>p.id===draft.projectId);if(!p){p={id:id(),number:draft.number.trim(),customerProject:draft.customerProject,name:draft.name.trim(),address:draft.address.trim(),comment:draft.comment.trim(),customer:next.customers.find(c=>c.prefix===draft.number.slice(0,4)).id,orders:[]};next.projects.unshift(p);}const at=now(),o={id:id(),title:draft.title.trim(),description:draft.description.trim(),due:draft.due,priority:draft.priority,assignee:draft.assignee,issuedBy:user,issuedAt:at,acceptedAt:null,status:'Ej påbörjad',participants:[],notes:[],events:[{id:id(),at,text:`${name(user)} skapade arbetsordern.`},{id:id(),at,text:`${name(user)} skickade arbetsordern till ${name(draft.assignee)}.`}]};p.orders.push(o);if(save(next)){pid=p.id;oid=o.id;screen='order';tab='Översikt';notice('Arbetsordern är skickad. Byt demoperson till utföraren för att acceptera.');render();}});}
function orderView(){const o=order(),p=project();if(!relevant(o)){screen='projects';render();return;}let actions='';if(o.assignee===user&&!o.acceptedAt)actions+='<button class="primary" id="accept">Acceptera arbetsorder</button>';if(o.participants.some(x=>x.user===user&&!x.acceptedAt))actions+='<button class="primary" id="acceptInvite">Acceptera inbjudan</button>';if(canWork(o)&&o.acceptedAt&&o.status==='Ej påbörjad')actions+='<button class="primary" id="start">Starta arbetet</button>';if(canWork(o)&&o.status==='Pågående')actions+='<button class="primary" id="complete">Markera som slutförd</button>';if(canWork(o)&&o.status==='Slutförd')actions+='<button class="secondary" id="reopen">Återöppna arbete</button>';
 app.innerHTML=`<button class="back" data-back>← Till projektet</button><div class="title"><div><small>${esc(p.number)}</small><h1>${esc(o.title)}</h1></div>${badge(o.status)}</div><p class="muted">${esc(p.address)} · ${esc(o.priority)} prioritet · Senast ${esc(o.due)}</p><div class="top-actions">${actions}</div><div class="tabs">${['Översikt','Dagbok','Bilder & filer','Utförare','Historik'].map(t=>`<button data-tab="${t}" class="${tab===t?'active':''}">${t}</button>`).join('')}</div><section class="card" id="orderContent"></section>`;
 bind('[data-back]','click',()=>{screen='project';pendingFiles=[];render();});bind('[data-tab]','click',e=>{tab=e.currentTarget.dataset.tab;pendingFiles=[];orderView();});bind('#accept','click',()=>mutate(o=>o.acceptedAt=now(),'accepterade arbetsordern.'));bind('#acceptInvite','click',()=>mutate(o=>o.participants.find(p=>p.user===user).acceptedAt=now(),'accepterade inbjudan.'));bind('#start','click',()=>mutate(o=>o.status='Pågående','startade arbetsordern.'));bind('#complete','click',()=>mutate(o=>o.status='Slutförd','markerade arbetsordern som slutförd.'));bind('#reopen','click',()=>mutate(o=>o.status='Pågående','återöppnade arbetsordern.'));
 const content=app.querySelector('#orderContent');
 if(tab==='Översikt')content.innerHTML=`<h3>Arbetsbeskrivning</h3><p class="description">${esc(o.description)}</p><div class="info">${[['Beställare',customer(p)],['Projekt',`${p.number} · ${p.name}`],['Utfärdad av',name(o.issuedBy)],['Utfärdad',date(o.issuedAt)],['Utförare',`${name(o.assignee)}${o.participants.length?' +'+o.participants.length:''}`],['Accepterad',o.acceptedAt?date(o.acceptedAt):'Inväntar accepterande']].map(([k,v])=>`<p><small>${k}</small><b>${esc(v)}</b></p>`).join('')}</div>`;
 if(tab==='Dagbok'){content.innerHTML=`<h3>Dagbok</h3>${canWork(o)&&o.status!=='Slutförd'?'<form class="compose" id="noteForm"><textarea name="note" aria-label="Dagboksanteckning" placeholder="Vad har du gjort idag?"></textarea><div id="pending" class="chips"></div><div class="compose-actions"><label class="upload">＋ Bilder / filer<input type="file" id="file" multiple accept="image/*,.pdf,.txt,.doc,.docx"></label><button>Spara anteckning</button></div><p class="date-line">Högst 5 filer per anteckning · 2 MB per fil</p></form>':`<p class="muted">${o.status==='Slutförd'?'Återöppna arbetsordern för att skriva fler anteckningar.':'Acceptera arbetsordern eller inbjudan för att skriva i dagboken.'}</p>`}${o.notes.map(n=>`<article class="entry"><time>${date(n.at)} · ${esc(name(n.author))}</time><p class="description">${esc(n.text)}</p>${filesHtml(n.files)}</article>`).join('')||'<div class="empty">Ingen anteckning ännu.</div>'}`;
 bind('#file','change',async e=>{const chosen=[...e.target.files];e.target.value='';if(chosen.length+pendingFiles.length>5||chosen.some(f=>f.size>2*1024*1024)){notice('Högst 5 filer, max 2 MB per fil.');return;}try{const added=await Promise.all(chosen.map(f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({id:id(),name:f.name,type:f.type,data:r.result});r.onerror=reject;r.readAsDataURL(f);})));pendingFiles.push(...added);app.querySelector('#pending').innerHTML=pendingFiles.map(f=>`<button type="button" data-remove="${f.id}">${esc(f.name)} ×</button>`).join('');bind('[data-remove]','click',e=>{pendingFiles=pendingFiles.filter(f=>f.id!==e.currentTarget.dataset.remove);e.currentTarget.remove();});}catch{notice('Filen kunde inte läsas.');}});
 bind('#noteForm','submit',e=>{e.preventDefault();const text=new FormData(e.target).get('note').trim();if(!text&&!pendingFiles.length)return;const next=structuredClone(data),target=next.projects.find(p=>p.id===pid).orders.find(o=>o.id===oid),at=now();target.notes.unshift({id:id(),at,author:user,text,files:pendingFiles});target.events.push({id:id(),at,text:`${name(user)} lade till en dagboksanteckning med ${pendingFiles.length} filer.`});if(save(next)){pendingFiles=[];orderView();}});}
 if(tab==='Bilder & filer'){const files=o.notes.flatMap(n=>n.files);content.innerHTML=`<h3>Bilder & filer</h3><p class="muted">Bifoga bilder och filer tillsammans med en dagboksanteckning.</p>${filesHtml(files)}${files.length?'':'<div class="empty">Inga filer ännu.</div>'}`;}
 if(tab==='Utförare'){content.innerHTML=`<h3>Utförare & historik</h3><div class="person"><span><b>${esc(name(o.assignee))}</b><small>Ansvarig · ${o.acceptedAt?'Accepterad '+date(o.acceptedAt):'Inväntar accepterande'}</small></span></div>${o.participants.map(p=>`<div class="person"><span><b>${esc(name(p.user))}</b><small>Inbjuden av ${esc(name(p.invitedBy))} · ${date(p.invitedAt)}</small><small>${p.acceptedAt?'Accepterad '+date(p.acceptedAt):'Inväntar accepterande'}</small></span></div>`).join('')}${canWork(o)&&o.status!=='Slutförd'?`<form class="invite" id="inviteForm"><select aria-label="Välj kollega" required name="colleague"><option value="">Välj kollega</option>${data.people.filter(p=>p.role==='employee'&&p.id!==o.assignee&&!o.participants.some(x=>x.user===p.id)).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><button>Bjud in</button></form>`:''}`;bind('#inviteForm','submit',e=>{e.preventDefault();const colleague=new FormData(e.target).get('colleague');if(colleague)mutate(o=>o.participants.push({user:colleague,invitedBy:user,invitedAt:now(),acceptedAt:null}),`bjöd in ${name(colleague)}.`);});}
 if(tab==='Historik')content.innerHTML=`<h3>Automatisk historik</h3><p class="muted">Systemhändelser registreras automatiskt och kan inte redigeras i appen.</p><div class="timeline">${[...o.events].reverse().map(e=>`<p><small>${date(e.at)}</small><br>${esc(e.text)}</p>`).join('')}</div>`;
}
function administration(){if(!admin())return;app.innerHTML=`<h1>Team & beställare</h1><div class="admin-grid"><div class="card form"><h3>Företagets personal</h3>${data.people.map(p=>`<div class="person"><span>${esc(p.name)}</span><small>${p.role==='admin'?'Arbetsledare':'Utförare'}</small></div>`).join('')}<form id="personForm">${field('Ny kollega',input('name','','required'))}${field('Roll','<select name="role"><option value="employee">Utförare</option><option value="admin">Arbetsledare</option></select>')}<button class="primary full">Lägg till person</button></form></div><div class="card form"><h3>Beställare & prefix</h3>${data.customers.map(c=>`<div class="person"><b>${c.prefix}</b><span>${esc(c.name)}</span></div>`).join('')}<form id="customerForm">${field('Beställarens namn',input('name','','required'))}${field('Fyrsiffrigt prefix',input('prefix','','required pattern="[0-9]{4}" maxlength="4"'))}<button class="primary full">Lägg till beställare</button></form><h3 style="margin-top:30px">Kundprojekt</h3><div class="chips">${data.customerProjects.map(p=>`<span>${esc(p)}</span>`).join('')}</div><form id="customerProjectForm">${field('Nytt kundprojektnummer',input('number','','required'))}<button class="secondary">Lägg till kundprojekt</button></form></div></div>`;
 bind('#personForm','submit',e=>{e.preventDefault();const f=new FormData(e.target),n=f.get('name').trim();if(!n)return;const next=structuredClone(data);next.people.push({id:id(),name:n,role:f.get('role')});if(save(next))render();});bind('#customerForm','submit',e=>{e.preventDefault();const f=new FormData(e.target),prefix=f.get('prefix');if(data.customers.some(c=>c.prefix===prefix)){notice('Prefixet används redan.');return;}const next=structuredClone(data);next.customers.push({id:id(),name:f.get('name').trim(),prefix});if(save(next))render();});bind('#customerProjectForm','submit',e=>{e.preventDefault();const n=new FormData(e.target).get('number').trim();const next=structuredClone(data);if(n&&!next.customerProjects.includes(n))next.customerProjects.push(n);if(save(next))render();});}
document.getElementById('home').onclick=document.getElementById('navProjects').onclick=()=>{screen='projects';pendingFiles=[];render();};
document.getElementById('newBtn').onclick=document.getElementById('navNew').onclick=()=>beginNew();
document.getElementById('navAdmin').onclick=()=>{screen='admin';render();};
document.getElementById('user').onchange=e=>{user=e.target.value;screen='projects';query='';filter='Alla';pendingFiles=[];notice('');render();};
render();
