'use client';
import { useEffect, useState } from 'react';
import { Attachment, Order, Project, State, now, seed, status, uid } from '../lib/model';

const KEY = 'brief-v1';
const date = (value: string) => new Date(value).toLocaleString('sv-SE', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
const initials = (name: string) => name.split(' ').map(n => n[0]).slice(0, 2).join('');
type Draft = { projectId: string; number: string; customerProject: string; name: string; address: string; comment: string; title: string; description: string; due: string; priority: string; assignee: string };
const blank = (): Draft => ({ projectId: '', number: '', customerProject: '', name: '', address: '', comment: '', title: '', description: '', due: new Date().toISOString().slice(0, 10), priority: 'Normal', assignee: 'erik' });

export default function Home() {
    const [data, setData] = useState<State | null>(null);
    const [user, setUser] = useState('johan');
    const [screen, setScreen] = useState('projects');
    const [projectId, setProjectId] = useState('');
    const [orderId, setOrderId] = useState('');
    const [query, setQuery] = useState('');
    const [filter, setFilter] = useState('Alla');
    const [tab, setTab] = useState('Översikt');
    const [draft, setDraft] = useState<Draft>(blank);
    const [review, setReview] = useState(false);
    const [message, setMessage] = useState('');
    const [note, setNote] = useState('');
    const [files, setFiles] = useState<Attachment[]>([]);
    const [invite, setInvite] = useState('');
    const [newName, setNewName] = useState('');
    const [newPrefix, setNewPrefix] = useState('');
    const [newRole, setNewRole] = useState<'admin' | 'employee'>('employee');
    const [newCustomerProject, setNewCustomerProject] = useState('');
    useEffect(() => { try { const saved = localStorage.getItem(KEY); const value = saved ? JSON.parse(saved) : seed(); if (!Array.isArray(value.projects) || !Array.isArray(value.people) || !Array.isArray(value.customers) || !Array.isArray(value.customerProjects)) throw Error(); setData(value); } catch { setData(seed()); setMessage('Sparade data kunde inte läsas. Demodata har laddats.'); } }, []);
    if (!data) return <main className="loading">bref<span>Laddar din arbetsyta…</span></main>;
    const person = data.people.find(p => p.id === user)!;
    const admin = person.role === 'admin';
    const name = (id: string) => data.people.find(p => p.id === id)?.name || 'Okänd användare';
    const customer = (id: string) => data.customers.find(c => c.id === id)?.name || 'Okänd beställare';
    const relevant = (o: Order) => admin || o.assignee === user || o.participants.some(p => p.user === user);
    const project = data.projects.find(p => p.id === projectId);
    const order = project?.orders.find(o => o.id === orderId);
    const visible = data.projects.filter(p => admin || p.orders.some(relevant));
    const projects = visible.filter(p => `${p.number} ${p.customerProject} ${p.name} ${p.address} ${customer(p.customer)} ${p.orders.map(o => name(o.assignee)).join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'Alla' || status(p) === filter));
    function save(next: State) { try { localStorage.setItem(KEY, JSON.stringify(next)); setData(next); return true; } catch { setMessage('Lagringsutrymmet är fullt. Ändringen sparades inte. Välj mindre filer.'); return false; } }
    function updateOrder(action: (o: Order) => void, text: string) { if (!project || !order) return; const next = structuredClone(data!); const o = next.projects.find(p => p.id === project.id)!.orders.find(o => o.id === order.id)!; action(o); o.events.push({ id: uid(), at: now(), text: `${name(user)} ${text}` }); save(next); }
    function openProject(p: Project) { setProjectId(p.id); setScreen('project'); setOrderId(''); setTab('Översikt'); setNote(''); setFiles([]); }
    function openOrder(o: Order) { setOrderId(o.id); setScreen('order'); setTab('Översikt'); setInvite(''); setNote(''); setFiles([]); }
    function createOrder() { const target = data!.projects.find(p => p.id === draft.projectId); setDraft({ ...blank(), ...(target ? { projectId: target.id, number: target.number, customerProject: target.customerProject, name: target.name, address: target.address, comment: target.comment } : {}) }); setReview(false); setScreen('new'); }
    function sendOrder() {
        const next = structuredClone(data!); const at = now(); let p = next.projects.find(p => p.id === draft.projectId);
        const found = next.customers.find(c => c.prefix === draft.number.slice(0, 4));
        if (!p && !found) { setMessage('Projektnumret behöver ett registrerat beställarprefix.'); return; }
        if (!p && next.projects.some(p => p.number.toLowerCase() === draft.number.trim().toLowerCase())) { setMessage('Projektnumret finns redan. Välj befintligt projekt.'); return; }
        if (!p) { p = { id: uid(), number: draft.number.trim(), customerProject: draft.customerProject, name: draft.name.trim(), address: draft.address.trim(), comment: draft.comment.trim(), customer: found!.id, orders: [] }; next.projects.unshift(p); }
        const o: Order = { id: uid(), title: draft.title.trim(), description: draft.description.trim(), due: draft.due, priority: draft.priority, assignee: draft.assignee, issuedBy: user, issuedAt: at, status: 'Ej påbörjad', participants: [], notes: [], events: [{ id: uid(), at, text: `${name(user)} skapade arbetsordern.` }, { id: uid(), at, text: `${name(user)} skickade arbetsordern till ${name(draft.assignee)}.` }] }; p.orders.push(o);
        if (save(next)) { setProjectId(p.id); setOrderId(o.id); setScreen('order'); setTab('Översikt'); setMessage('Arbetsordern är skickad. Byt demoperson till utföraren för att acceptera.'); }
    }
    async function addFiles(list: FileList | null) { if (!list) return; const chosen = Array.from(list); if (chosen.some(f => f.size > 2 * 1024 * 1024) || files.length + chosen.length > 5) { setMessage('Välj högst 5 filer, max 2 MB per fil.'); return; } try { const added = await Promise.all(chosen.map(f => new Promise<Attachment>((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve({ id: uid(), name: f.name, type: f.type, data: String(r.result) }); r.onerror = () => reject(Error()); r.readAsDataURL(f); }))); setFiles(previous => [...previous, ...added]); } catch { setMessage('Filen kunde inte läsas. Försök igen.'); } }
    const acceptedParticipant = order?.participants.find(p => p.user === user)?.acceptedAt;
    const canWork = !!order && (admin || (order.assignee === user && !!order.acceptedAt) || !!acceptedParticipant);
    const draftCustomer = data.customers.find(c => c.prefix === draft.number.slice(0, 4));
    const heading = screen === 'projects' ? 'Dina projekt' : screen === 'new' ? (review ? 'Granska arbetsorder' : 'Ny arbetsorder') : screen === 'admin' ? 'Team & beställare' : screen === 'order' ? order?.title : project?.name;
    return <>
        <header className="header"><button className="brand" onClick={() => setScreen('projects')} aria-label="Brief, projektöversikt"><img src="/brand/brief-horizontal.png" alt="brēf" className="brand-image" /></button><nav><button className={screen === 'projects' ? 'nav-active' : ''} onClick={() => setScreen('projects')}>Projekt</button>{admin && <button className={screen === 'admin' ? 'nav-active' : ''} onClick={() => setScreen('admin')}>Team & beställare</button>}</nav><label className="user"><span className="avatar">{initials(person.name)}</span><span><small>DEMOPERSON</small><select aria-label="Byt demoperson" value={user} onChange={e => { setUser(e.target.value); setScreen('projects'); setQuery(''); setFilter('Alla'); setFiles([]); setNote(''); }}>{data.people.map(p => <option key={p.id} value={p.id}>{p.name} · {p.role === 'admin' ? 'Arbetsledare' : 'Utförare'}</option>)}</select></span></label></header>
        <div className="demo-bar"><span className="tiny-dot" />Första versionen · Demoläge med lokal lagring<span className="desktop-only">Brief — uttalas brēf</span></div>
        <main>
            {message && <div role="status" className="notice">{message}<button aria-label="Stäng meddelande" onClick={() => setMessage('')}>×</button></div>}
            {screen !== 'projects' && <button className="back" onClick={() => { if (screen === 'order') setScreen('project'); else setScreen('projects'); }}>← {screen === 'order' ? 'Till projektet' : 'Till projektöversikten'}</button>}
            <div className="page-heading"><div><div className="eyebrow">{screen === 'projects' ? 'ÖVERBLICK' : screen === 'order' ? project?.number : screen === 'project' ? `${project?.number} / ${project ? customer(project.customer) : ''}` : 'BRIEF'}</div><h1>{heading}</h1><p>{screen === 'projects' ? 'Allt arbete. Ett tydligt nästa steg.' : screen === 'project' ? project?.address : screen === 'new' ? 'Från uppdrag till utförare, utan omvägar.' : screen === 'admin' ? 'Företagets egen personal och projektkopplingar.' : order?.description}</p></div>{admin && (screen === 'projects' || screen === 'project') && <button className="primary" onClick={() => { setDraft({ ...blank(), projectId: screen === 'project' ? projectId : '' }); setReview(false); if (screen === 'project' && project) setDraft({ ...blank(), projectId: project.id, number: project.number, customerProject: project.customerProject, name: project.name, address: project.address, comment: project.comment }); setScreen('new'); }}>＋ Ny arbetsorder</button>}</div>
            {screen === 'projects' && <>
                <div className="stats">{['Alla', 'Ej påbörjad', 'Pågående', 'Slutförd'].map((s, i) => <button key={s} className={filter === s ? 'stat selected' : 'stat'} onClick={() => setFilter(s)}><span>{['Projekt totalt', 'Att påbörja', 'Under arbete', 'Slutförda'][i]}</span><strong>{s === 'Alla' ? visible.length : visible.filter(p => status(p) === s).length}</strong><span className={`stat-dot dot-${i}`} /></button>)}</div>
                <section className="panel"><div className="list-toolbar"><h2>Projektöversikt <span>{projects.length}</span></h2><label className="search"><span>⌕</span><input aria-label="Sök projekt" placeholder="Sök projektnummer, adress eller utförare…" value={query} onChange={e => setQuery(e.target.value)} /></label></div>
                    <div className="table-wrap"><table><thead><tr>{['Kundprojektnr', 'Projektnr / Projekt', 'Adress', 'Utförare', 'Status', 'Kommentar', ''].map(t => <th key={t}>{t}</th>)}</tr></thead><tbody>{projects.map(p => <tr key={p.id}><td className="muted">{p.customerProject}</td><td><button className="project-link" onClick={() => openProject(p)}>{p.number}<strong>{p.name}</strong></button></td><td>{p.address}</td><td><div className="names">{[...new Set(p.orders.filter(relevant).map(o => o.assignee))].map(id => <span key={id} title={name(id)} className="avatar">{initials(name(id))}</span>)}{!p.orders.length && '—'}</div></td><td><Badge value={status(p)} /></td><td className="comment">{p.comment || '—'}</td><td><button onClick={() => openProject(p)} aria-label={`Öppna ${p.name}`}>↗</button></td></tr>)}</tbody></table></div>
                    {!projects.length && <div className="empty"><h3>Inga projekt här ännu</h3><p>{query ? 'Prova en annan sökning.' : admin ? 'Skapa en arbetsorder för att lägga till ett projekt.' : 'Dina tilldelade arbetsorder visas här.'}</p></div>}
                </section><div className="quiet-footer"><span>En arbetsyta för hela vägen till klart.</span><span>BRIEF v0.1</span></div>
            </>}
            {screen === 'project' && project && <><div className="project-meta"><Badge value={status(project)} /><span>Kundprojekt {project.customerProject}</span><span>{project.comment}</span></div><section className="panel order-list"><div className="list-toolbar"><h2>Arbetsorder</h2><span className="muted">{project.orders.filter(relevant).length} uppdrag</span></div>{project.orders.filter(relevant).map(o => <button className="order-row" key={o.id} onClick={() => openOrder(o)}><div className="order-icon">↗</div><div><h3>{o.title}</h3><p>{name(o.assignee)} · Senast {o.due} · {o.priority} prioritet</p></div><Badge value={o.status} /><span>→</span></button>)}{!project.orders.filter(relevant).length && <div className="empty">Skapa projektets första arbetsorder.</div>}</section></>}
            {screen === 'new' && admin && <section className="form-panel">{!review ? <form onSubmit={e => { e.preventDefault(); if (!draft.projectId && !draftCustomer) { setMessage('Lägg först till beställaren med rätt fyrsiffrigt prefix under Team & beställare.'); return; } setReview(true); }}>
                <div className="form-section"><span className="section-number">01</span><h2>Projektet</h2></div>
                <Field label="Projekt"><select value={draft.projectId} onChange={e => { const p = data.projects.find(p => p.id === e.target.value); setDraft(p ? { ...draft, projectId: p.id, number: p.number, customerProject: p.customerProject, name: p.name, address: p.address, comment: p.comment } : { ...draft, projectId: '', number: '', name: '', address: '', customerProject: '', comment: '' }); }}><option value="">Skapa nytt projekt</option>{data.projects.map(p => <option key={p.id} value={p.id}>{p.number} · {p.name}</option>)}</select></Field>
                {!draft.projectId && <><div className="form-grid"><Field label="Kundprojektnummer"><input list="customer-projects" required value={draft.customerProject} onChange={e => setDraft({ ...draft, customerProject: e.target.value })} /><datalist id="customer-projects">{data.customerProjects.map(p => <option key={p} value={p} />)}</datalist></Field><Field label="Företagets projektnummer"><input required pattern="[0-9]{4}-.+" placeholder="1842-026" value={draft.number} onChange={e => setDraft({ ...draft, number: e.target.value })} /></Field></div><div className="customer-match">↳ {draftCustomer ? draftCustomer.name : 'De fyra första siffrorna identifierar beställaren.'}</div><Field label="Projektnamn"><input required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></Field><Field label="Adress"><input required value={draft.address} onChange={e => setDraft({ ...draft, address: e.target.value })} /></Field><Field label="Projektkommentar (valfri)"><input value={draft.comment} onChange={e => setDraft({ ...draft, comment: e.target.value })} /></Field></>}
                <div className="form-section"><span className="section-number">02</span><h2>Uppdraget</h2></div><Field label="Arbetsorderrubrik"><input required value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></Field><Field label="Arbetsbeskrivning"><textarea required rows={4} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></Field><div className="form-grid"><Field label="Datum"><input type="date" required value={draft.due} onChange={e => setDraft({ ...draft, due: e.target.value })} /></Field><Field label="Prioritet"><select value={draft.priority} onChange={e => setDraft({ ...draft, priority: e.target.value })}>{['Låg', 'Normal', 'Hög'].map(v => <option key={v}>{v}</option>)}</select></Field></div><Field label="Ansvarig utförare"><select required value={draft.assignee} onChange={e => setDraft({ ...draft, assignee: e.target.value })}>{data.people.filter(p => p.role === 'employee').map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><div className="form-actions"><button type="button" onClick={() => setScreen('projects')}>Avbryt</button><button className="primary">Granska arbetsorder →</button></div>
            </form> : <><div className="eyebrow">REDO ATT SKICKA</div><h2>{draft.title}</h2><p className="description">{draft.description}</p><dl className="details"><dt>Projekt</dt><dd>{draft.number} · {draft.name}</dd><dt>Beställare</dt><dd>{draftCustomer?.name}</dd><dt>Kundprojekt</dt><dd>{draft.customerProject}</dd><dt>Adress</dt><dd>{draft.address}</dd><dt>Utförare</dt><dd>{name(draft.assignee)}</dd><dt>Datum / prioritet</dt><dd>{draft.due} · {draft.priority}</dd></dl><div className="form-actions"><button onClick={() => setReview(false)}>← Ändra</button><button className="primary" onClick={sendOrder}>Skicka arbetsorder ↗</button></div></>}</section>}
            {screen === 'order' && order && relevant(order) && <>
                <div className="order-summary"><Badge value={order.status} /><span>{order.priority} prioritet</span><span>Senast {order.due}</span><button className="people-link" onClick={() => setTab('Utförare')}>Utförare › {name(order.assignee)}{order.participants.length ? ` +${order.participants.length}` : ''}</button></div>
                <div className="work-actions">{order.assignee === user && !order.acceptedAt && <button className="primary" onClick={() => updateOrder(o => { o.acceptedAt = now(); }, 'accepterade arbetsordern.')}>Acceptera arbetsorder</button>}{order.participants.some(p => p.user === user && !p.acceptedAt) && <button className="primary" onClick={() => updateOrder(o => { o.participants.find(p => p.user === user)!.acceptedAt = now(); }, 'accepterade inbjudan.')}>Acceptera inbjudan</button>}{canWork && order.acceptedAt && order.status === 'Ej påbörjad' && <button className="primary" onClick={() => updateOrder(o => { o.status = 'Pågående'; }, 'startade arbetsordern.')}>Starta arbetet →</button>}{canWork && order.status === 'Pågående' && <button className="primary" onClick={() => updateOrder(o => { o.status = 'Slutförd'; }, 'markerade arbetsordern som slutförd.')}>✓ Markera som slutförd</button>}{canWork && order.status === 'Slutförd' && <button onClick={() => updateOrder(o => { o.status = 'Pågående'; }, 'återöppnade arbetsordern.')}>Återöppna arbete</button>}</div>
                <div className="tabs">{['Översikt', 'Dagbok', 'Bilder & filer', 'Utförare', 'Historik'].map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t}{t === 'Dagbok' && <small>{order.notes.length}</small>}</button>)}</div>
                <section className="panel content-panel">
                    {tab === 'Översikt' && <div className="overview-grid"><div><div className="eyebrow">ARBETSBESKRIVNING</div><h2>{order.title}</h2><p className="description">{order.description}</p><div className="next-step"><span>→</span><div><strong>Nästa steg</strong><p>{order.status === 'Slutförd' ? 'Arbetet är klart. Dagbok och historik finns kvar här.' : !order.acceptedAt ? `${name(order.assignee)} behöver acceptera arbetsordern.` : order.status === 'Ej påbörjad' ? 'Starta arbetet när du är på plats.' : 'Dokumentera arbetet i dagboken och bifoga bilder.'}</p></div></div></div><dl className="details"><dt>Utfärdad av</dt><dd>{name(order.issuedBy)}</dd><dt>Utfärdad</dt><dd>{date(order.issuedAt)}</dd><dt>Utförare</dt><dd>{name(order.assignee)}</dd><dt>Accepterad</dt><dd>{order.acceptedAt ? date(order.acceptedAt) : 'Inväntar accepterande'}</dd></dl></div>}
                    {tab === 'Dagbok' && <><h2>Arbetet, som det händer.</h2>{canWork && order.status !== 'Slutförd' ? <form className="note-form" onSubmit={e => { e.preventDefault(); if (!note.trim() && !files.length) return; const next = structuredClone(data); const o = next.projects.find(p => p.id === projectId)!.orders.find(o => o.id === orderId)!; const at = now(); o.notes.unshift({ id: uid(), at, author: user, text: note.trim(), files }); o.events.push({ id: uid(), at, text: `${name(user)} lade till en dagboksanteckning${files.length ? ` med ${files.length} filer` : ''}.` }); if (save(next)) { setNote(''); setFiles([]); } }}><textarea aria-label="Dagboksanteckning" placeholder="Vad har du gjort idag?" rows={3} value={note} onChange={e => setNote(e.target.value)} /><div className="file-chips">{files.map(f => <button type="button" key={f.id} onClick={() => setFiles(files.filter(x => x.id !== f.id))}>{f.name} ×</button>)}</div><div className="form-actions"><label className="file-button">＋ Bilder / filer<input type="file" multiple accept="image/*,.pdf,.txt,.doc,.docx" onChange={e => { void addFiles(e.target.files); e.target.value = ''; }} /></label><button className="primary" disabled={!note.trim() && !files.length}>Spara anteckning</button></div><small className="muted">Högst 5 filer per anteckning · 2 MB per fil</small></form> : <p className="muted">{order.status === 'Slutförd' ? 'Arbetsordern är slutförd. Återöppna för att lägga till anteckningar.' : 'Acceptera arbetsordern eller inbjudan för att skriva i dagboken.'}</p>}{order.notes.map(n => <article className="diary-entry" key={n.id}><div className="entry-head"><span className="avatar">{initials(name(n.author))}</span><strong>{name(n.author)}</strong><time>{date(n.at)}</time></div><p className="description">{n.text}</p><Files files={n.files} /></article>)}{!order.notes.length && <div className="empty">Dagboken väntar på den första anteckningen.</div>}</>}
                    {tab === 'Bilder & filer' && <><h2>Bilder & filer</h2><p className="muted">Lägg till filer tillsammans med en anteckning i dagboken.</p><Files files={order.notes.flatMap(n => n.files)} />{!order.notes.some(n => n.files.length) && <div className="empty">Inga bifogade filer ännu.</div>}</>}
                    {tab === 'Utförare' && <><h2>Utförare & historik</h2><div className="person-row"><span className="avatar">{initials(name(order.assignee))}</span><div><strong>{name(order.assignee)}</strong><p>Ansvarig · {order.acceptedAt ? `Accepterad ${date(order.acceptedAt)}` : 'Inväntar accepterande'}</p></div></div>{order.participants.map(p => <div className="person-row" key={p.user}><span className="avatar">{initials(name(p.user))}</span><div><strong>{name(p.user)}</strong><p>Inbjuden av {name(p.invitedBy)} · {date(p.invitedAt)}</p><p>{p.acceptedAt ? `Accepterad ${date(p.acceptedAt)}` : 'Inväntar accepterande'}</p></div></div>)}{canWork && order.status !== 'Slutförd' && <form className="invite-form" onSubmit={e => { e.preventDefault(); if (!invite) return; updateOrder(o => { o.participants.push({ user: invite, invitedBy: user, invitedAt: now() }); }, `bjöd in ${name(invite)}.`); setInvite(''); }}><Field label="Bjud in en kollega"><select required value={invite} onChange={e => setInvite(e.target.value)}><option value="">Välj från företagets personal</option>{data.people.filter(p => p.role === 'employee' && p.id !== order.assignee && !order.participants.some(x => x.user === p.id)).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><button className="primary" disabled={!invite}>Bjud in kollega</button></form>}</>}
                    {tab === 'Historik' && <><h2>Hela vägen, automatiskt dokumenterad.</h2><p className="muted">Systemhändelser registreras vid varje steg och kan inte redigeras i appen.</p><ol className="timeline">{[...order.events].reverse().map(e => <li key={e.id}><span /><div><time>{date(e.at)}</time><p>{e.text}</p></div></li>)}</ol></>}
                </section>
            </>}
            {screen === 'admin' && admin && <div className="admin-grid"><section className="panel content-panel"><h2>Företagets personal</h2>{data.people.map(p => <div className="person-row" key={p.id}><span className="avatar">{initials(p.name)}</span><div><strong>{p.name}</strong><p>{p.role === 'admin' ? 'Arbetsledare' : 'Utförare'}</p></div></div>)}<form onSubmit={e => { e.preventDefault(); if (!newName.trim()) return; const next = structuredClone(data); next.people.push({ id: uid(), name: newName.trim(), role: newRole }); if (save(next)) setNewName(''); }}><Field label="Ny kollega"><input required placeholder="För- och efternamn" value={newName} onChange={e => setNewName(e.target.value)} /></Field><Field label="Roll"><select value={newRole} onChange={e => setNewRole(e.target.value as 'admin' | 'employee')}><option value="employee">Utförare</option><option value="admin">Arbetsledare</option></select></Field><button className="primary">Lägg till person</button></form></section><section className="panel content-panel"><h2>Beställare & prefix</h2>{data.customers.map(c => <div className="customer-row" key={c.id}><code>{c.prefix}</code><strong>{c.name}</strong></div>)}<form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (data.customers.some(c => c.prefix === newPrefix)) { setMessage('Prefixet används redan.'); return; } const next = structuredClone(data); next.customers.push({ id: uid(), name: String(f.get('customer')).trim(), prefix: newPrefix }); if (save(next)) { setNewPrefix(''); e.currentTarget.reset(); } }}><Field label="Beställarens namn"><input name="customer" required /></Field><Field label="Fyrsiffrigt prefix"><input required pattern="[0-9]{4}" maxLength={4} value={newPrefix} onChange={e => setNewPrefix(e.target.value)} /></Field><button className="primary">Lägg till beställare</button></form><h2 className="spaced">Kundprojekt</h2><div className="file-chips">{data.customerProjects.map(p => <span key={p}>{p}</span>)}</div><form onSubmit={e => { e.preventDefault(); const value = newCustomerProject.trim(); if (!value) return; const next = structuredClone(data); if (!next.customerProjects.includes(value)) next.customerProjects.push(value); if (save(next)) setNewCustomerProject(''); }}><Field label="Nytt kundprojektnummer"><input required value={newCustomerProject} onChange={e => setNewCustomerProject(e.target.value)} /></Field><button>Lägg till kundprojekt</button></form></section></div>}
        </main><footer><span className="footer-brand">brēf</span><span>Ordning i arbetet. Utrymme för jobbet.</span><span>Lokal demo · Sparas på den här enheten</span></footer>
    </>;
}
function Badge({ value }: { value: string }) { return <span className={`badge ${value === 'Pågående' ? 'progress' : value === 'Slutförd' ? 'complete' : 'pending'}`}><i />{value}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Files({ files }: { files: Attachment[] }) { return <div className="attachments">{files.map(f => <a key={f.id} href={f.data} download={f.name}>{f.type.startsWith('image/') ? <img src={f.data} alt={f.name} /> : <div className="file-icon">↧</div>}<span>{f.name}</span></a>)}</div>; }

